Repository SU-SWS/stanford_profile_helper, pull requests merged in 2020-09, with the labels that each got.

#18 D8CORE-2040 Update styles for react paragraphs V2
  composer.json
  modules/stanford_profile_drush/src/Commands/StanfordProfileCommands.php
  modules/stanford_profile_drush/tests/src/Kernel/Commands/StanfordProfileCommandsTest.php
  modules/stanford_profile_styles/stanford_profile_styles.module
Labels: size/s

#16 D8CORE-2533: external link adjustments
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
Labels: size/xs

#15 D8CORE-1609: Super Footer and Global Messages
  .sass-lint.yml
  modules/stanford_profile_styles/.nvmrc
  modules/stanford_profile_styles/assets/svg/lock-solid.svg
  modules/stanford_profile_styles/assets/svg/lock.svg
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.footer.super-footer.css
  modules/stanford_profile_styles/lib/scss/blocks/config_pages.super-footer.scss
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_profile_styles/webpack.config.js
  stanford_profile_helper.module
Labels: size/xl

#20 D8CORE-2420: Rebuild router on taxonomy change to fix bug with taxonomy_menu
  stanford_profile_helper.module
Labels: size/xs

#21 D8CORE-2490: Name key changes.
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  stanford_profile_helper.module
Labels: size/xs

#23 D8CORE-2521: Add hook for field permission on open embed field.
  stanford_profile_helper.module
Labels: size/xs

#24 8.1.2
  .sass-lint.yml
  CHANGELOG.md
  composer.json
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/src/Commands/StanfordProfileCommands.php
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_drush/tests/src/Kernel/Commands/StanfordProfileCommandsTest.php
  modules/stanford_profile_styles/.nvmrc
  modules/stanford_profile_styles/assets/svg/arrow-right.svg
  modules/stanford_profile_styles/assets/svg/arrow-up-right.svg
  modules/stanford_profile_styles/assets/svg/lock-solid.svg
  modules/stanford_profile_styles/assets/svg/lock.svg
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.ckeditor.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.footer.super-footer.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.paragraph.wysiwyg.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/blocks/config_pages.super-footer.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/react_paragraphs/_multirow.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_profile_styles/webpack.config.js
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/xl

#25 Fix composer requirements
  composer.json
Labels: patch, size/xs

#26 Added presave to remove all field permissions from field storage that arent needed
  stanford_profile_helper.module
Labels: size/xs

#27 D8CORE-2644: Added additional help text and snow form links
  stanford_profile_helper.module
Labels: size/xs
