Repository SU-SWS/stanford_profile_helper, pull requests merged in 2020-11, with the labels that each got.

#39 D8core-2765 Styles and icons for mailto buttons
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
Labels: size/xs

#43 V1.5.0 tweaks
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.layout.stanford_page.full.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
Labels: size/xs

#45 D8CORE-2570 Update hook to create the intro blocks
  stanford_profile_helper.post_update.php
Labels: size/xs

#46 D8CORE-2951 D8CORE-2952 Style adjustments for people cards
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.module
Labels: size/xs

#48 "8.x-1.x 8.1.6
  CHANGELOG.md
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.layout.stanford_page.full.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/_modular_spacing.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
  stanford_profile_helper.post_update.php
  tests/codeception/acceptance/ContentCest.php
Labels: patch, size/s

#49 Change the github actions to tag PRs on master
  .github/workflows/tag_commits_to_master.yml
Labels: size/xs

#51 D8CORE-2765: removing action link and changing colors for mailto links
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
Labels: size/xs

#50 D9 Ready
  composer.json
  modules/stanford_profile_drush/tests/src/Kernel/Commands/StanfordProfileCommandsTest.php
  src/StanfordPreRenderer.php
  stanford_profile_helper.module
  tests/src/Kernel/StanfordPreRendererTest.php
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: size/s

#54 D8CORE-2668 Removed title attribute from taxonomy menu items
  stanford_profile_helper.module
Labels: size/xs
