Repository SU-SWS/stanford_profile_helper, pull requests merged in 2020-08, with the labels that each got.

#10 D8CORE-1472: Config pages lockup Form helpers
  .gitignore
  composer.json
  src/Config/ConfigOverrides.php
  stanford_profile_helper.module
  stanford_profile_helper.services.yml
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: size/m

#12 D8CORE-2497: setting max-width to 980 like the cards
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
Labels: size/xs

#13 8.1.1
  .gitignore
  CHANGELOG.md
  composer.json
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  src/Config/ConfigOverrides.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
  stanford_profile_helper.services.yml
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: patch, size/m

#14 D8CORE-2322: fixing the margins on the full width page
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/paragraph-types/react_paragraphs/_multirow.scss
Labels: patch, size/xs

#11 D8CORE-2201, D8CORE-2448: hiding the default external link
  modules/stanford_profile_styles/assets/svg/arrow-right.svg
  modules/stanford_profile_styles/assets/svg/arrow-up-right.svg
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
Labels: patch, size/xs

#19 D8CORE 2541 Added padding to images in the wysiwyg paragraph type
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.ckeditor.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.paragraph.wysiwyg.css
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_paragraph.scss
Labels: size/xs
