Repository SU-SWS/stanford_profile_helper, pull requests merged in 2020-10, with the labels that each got.

#28 D8CORE-2613: Delete taxonomy menu links when the parents change
  stanford_profile_helper.module
Labels: size/xs

#29 8.1.4
  CHANGELOG.md
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/s

#30 D8CORE-2184 Adjust taxonomy terms to only 1 parent
  stanford_profile_helper.module
Labels: size/xs

#31 D8CORE-2184 Add element validate to tweak the submitted value
  stanford_profile_helper.module
Labels: size/xs

#32 8.1.5
  CHANGELOG.md
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/xs

#33 D8CORE-000 Fixed breaking if the parent menu item is external
  stanford_profile_helper.module
  tests/codeception/acceptance/ContentCest.php
Labels: size/xs

#34 D8CORE-2856 Remove unwanted views from the list paragraph type
  stanford_profile_helper.module
Labels: size/xs

#35 D8CORE-2875: Limit paragraph choices for now
  stanford_profile_helper.module
Labels: size/xs

#36 D8CORE-2738 Reduce list paragraph max width
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
Labels: size/xs

#37 Adjusted the list paragraph styles for grid displays
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
Labels: size/xs

#38 D8CORE-2285: adding the css to the pages that need the ckeditor style…
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/stanford_profile_styles.module
Labels: size/xs

#40 D8CORE-2780 People card images are circles
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
Labels: size/xs

#41 D8CORE-2183 Keep the relations fieldset open by default on term form
  stanford_profile_helper.module
Labels: size/xs

#42 D8CORE-000 List and content reference paragraph style helpers
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/_modular_spacing.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
  stanford_profile_helper.module
Labels: size/xs
