Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-01, with the labels that each got.

#59 Updated circleci testing
  .circleci/config.yml
Labels: size/xs

#60 D8CORE-3142: Styling some padding for the su-intro
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.ckeditor.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.paragraph.wysiwyg.css
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_paragraph.scss
Labels: size/xs

#63 D8CORE-3052: Centering the title and button for teasers.
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
Labels: size/l

#62 D8CORE-3263 Gallery paragraph styling
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/admin/field_widgets.css
  modules/stanford_profile_styles/dist/css/base/admin/node_forms.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/dist/css/component/paragraph/spacer.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/base/.gitkeep
  modules/stanford_profile_styles/lib/scss/base/admin/_node_form_stanford_page.scss
  modules/stanford_profile_styles/lib/scss/base/admin/ckeditor.scss
  modules/stanford_profile_styles/lib/scss/base/admin/field_widgets.scss
  modules/stanford_profile_styles/lib/scss/base/admin/node_forms.scss
  modules/stanford_profile_styles/lib/scss/base/stanford_profile_styles.scss
  modules/stanford_profile_styles/lib/scss/component/.gitkeep
  modules/stanford_profile_styles/lib/scss/component/blocks/config_pages.super-footer.scss
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/gallery/index.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/react_paragraphs/_multirow.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/react_paragraphs/index.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/spacer/_spacer.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/spacer/index.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_buttons.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_headings.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_lists.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_table.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_wysiwyg.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/index.scss
  modules/stanford_profile_styles/lib/scss/layout/.gitkeep
  modules/stanford_profile_styles/lib/scss/state/.gitkeep
  modules/stanford_profile_styles/lib/scss/theme/.gitkeep
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_profile_styles/webpack.config.js
Labels: size/s

#67 Fixed ckeditor styles path
  modules/stanford_profile_styles/stanford_profile_styles.module
Labels: size/xs

#65 D8CORE-3053: fixing margin bottom on lists as cards
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#64 D8CORE-3164: fixing news list alignment.
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
Labels: size/s

#69 D8CORE-3163: adding a little space on lists in columns
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/package-lock.json
Labels: size/xs
