Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-04, with the labels that each got.

#96 D8CORE-4020: fixing the mixing of branches
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#89 D8CORE-3686: Intranet styles.
  modules/stanford_intranet/dist/assets/svg/lock-solid.svg
  modules/stanford_intranet/dist/css/base/intranet.css
  modules/stanford_intranet/dist/css/base/stanford_intranet.config.css
  modules/stanford_intranet/lib/assets/svg/lock-solid.svg
  modules/stanford_intranet/lib/scss/base/_link-icon-before.scss
  modules/stanford_intranet/lib/scss/base/intranet.scss
  modules/stanford_intranet/lib/scss/base/stanford_intranet.config.scss
  modules/stanford_intranet/stanford_intranet.module
  modules/stanford_intranet/webpack.config.js
Labels: size/s

#98 D8CORE-2766 Tests
  src/Plugin/Validation/Constraint/GlobalMessageConstraintValidator.php
  tests/src/Unit/Plugin/Validation/Constraint/GlobalMessageConstraintValidatorTest.php
Labels: size/xs

#88 D8CORE-2766: adding constraint for global message validation
  src/Plugin/Validation/Constraint/GlobalMessageConstraint.php
  src/Plugin/Validation/Constraint/GlobalMessageConstraintValidator.php
  stanford_profile_helper.module
  tests/src/Unit/Plugin/Validation/Constraint/GlobalMessageConstraintValidatorTest.php
Labels: size/s

#90 D8CORE-3254: basic page plus functionality
  modules/stanford_basic_page_types/.nvmrc
  modules/stanford_basic_page_types/content/taxonomy_term/94320f2a-3bf4-4d29-8fc7-5bb97eedf10f.yml
  modules/stanford_basic_page_types/dist/assets/svg/caret-right.svg
  modules/stanford_basic_page_types/dist/css/component/basic-page-type-list.css
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/assets/caret-right.svg
  modules/stanford_basic_page_types/lib/scss/_config.scss
  modules/stanford_basic_page_types/lib/scss/component/basic-page-type-list/_basic-page-type-list.scss
  modules/stanford_basic_page_types/lib/scss/component/basic-page-type-list/index.scss
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/index.scss
  modules/stanford_basic_page_types/package-lock.json
  modules/stanford_basic_page_types/package.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.module
  modules/stanford_basic_page_types/templates/components/basic_page_types_list/basic-page-types-list.twig
  modules/stanford_basic_page_types/templates/components/basic_page_types_list/basic-page-types-list.ui_patterns.yml
  modules/stanford_basic_page_types/webpack.config.js
  modules/stanford_profile_styles/stanford_profile_styles.module
  stanford_profile_helper.module
Labels: patch, size/xl

#100 8.1.13
  CHANGELOG.md
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.module
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xs

#101 Basic Page+ styling hotfix
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
Labels: size/xs

#102 D8CORE-4115 Remove the "Unlock" button on node form
  stanford_profile_helper.module
Labels: size/xs

#103 D8CORE-4092: fixing up the padding to be on left and right
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#104 "8.x-1.x 8.1.14
  CHANGELOG.md
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/xs

#105 D8CORE-4097: Fixup the specificity problem for the local footer color
  modules/stanford_intranet/dist/css/base/intranet.css
  modules/stanford_intranet/lib/scss/base/intranet.scss
Labels: patch, size/xs
