Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-08, with the labels that each got.

#133 D8CORE-4690 Modify mathjax filter plugin to fix media and spacing issues
  composer.json
  src/Plugin/Filter/Mathjax.php
  stanford_profile_helper.module
  tests/src/Unit/Plugin/Filter/MathjaxTest.php
Labels: size/s

#131 D8CORE-4696 Fix the access for private images that were converted to png files via styles
  modules/stanford_intranet/stanford_intranet.module
Labels: size/xs

#135 8.1.22
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_intranet/stanford_intranet.module
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  src/Plugin/Filter/Mathjax.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
  tests/src/Unit/Plugin/Filter/MathjaxTest.php
Labels: size/s, patch

#137 D8CORE-4098: correcting the line contrast for the intranet wysiwyg table
  modules/stanford_intranet/dist/css/base/intranet.css
  modules/stanford_intranet/lib/scss/base/intranet.scss
Labels: size/xs
