Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-05, with the labels that each got.

#106 D8CORE-3970: adding teaser styles for event series
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#108 "8.x-1.x 8.1.15
  CHANGELOG.md
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/dist/css/base/intranet.css
  modules/stanford_intranet/lib/scss/base/intranet.scss
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xs

#110 D8CORE-2028 Change "People" to "Users" in the admin toolbar
  composer.json
  modules/stanford_profile_admin/src/Routing/RouteSubscriber.php
  modules/stanford_profile_admin/stanford_profile_admin.info.yml
  modules/stanford_profile_admin/stanford_profile_admin.module
  modules/stanford_profile_admin/stanford_profile_admin.services.yml
  modules/stanford_profile_admin/tests/src/Unit/Routing/RouteSubscriberTest.php
Labels: patch, size/s

#113 D8CORE-4104 Improve colorbox with javascript
  modules/stanford_profile_styles/js/colorbox.js
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
Labels: size/xs

#114 D8CORE-4178: Fixing the h2 that wasn't wrapping
  modules/stanford_basic_page_types/dist/css/component/basic-page-type-list.css
  modules/stanford_basic_page_types/lib/scss/component/basic-page-type-list/_basic-page-type-list.scss
Labels: patch, size/xs
