Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-06, with the labels that each got.

#118 D8CORE-4341: moving code from the person module.
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#119 "8.x-1.x 8.1.16
  .circleci/config.yml
  .github/pull_request_template.md
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/dist/css/component/basic-page-type-list.css
  modules/stanford_basic_page_types/lib/scss/component/basic-page-type-list/_basic-page-type-list.scss
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_admin/src/Routing/RouteSubscriber.php
  modules/stanford_profile_admin/stanford_profile_admin.info.yml
  modules/stanford_profile_admin/stanford_profile_admin.module
  modules/stanford_profile_admin/stanford_profile_admin.services.yml
  modules/stanford_profile_admin/tests/src/Unit/Routing/RouteSubscriberTest.php
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/js/colorbox.js
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/s

#121 8.1.17
  CHANGELOG.md
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xs

#123 Added and enabled the PDB module
  composer.json
  src/Plugin/Block/PDBlock.php
  src/Plugin/Derivative/ReactBlockDeriver.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/xs

#124 D8CORE-4236: fixing the event date alignment on cards and lists of cards.
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs
