Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-07, with the labels that each got.

#126 D8CORE-4194 Set the link title value for media caption paragraphs
  stanford_profile_helper.post_update.php
Labels: size/xs

#122 8.1.18
  CHANGELOG.md
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xs

#125 D8CORE-4225: clearing the floats if used in the wysiwyg for the medium and down breakpoint
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/react_paragraphs/_multirow.scss
Labels: patch, size/xs

#127 "8.x-1.x 8.1.19
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/react_paragraphs/_multirow.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  src/Plugin/Block/PDBlock.php
  src/Plugin/Derivative/ReactBlockDeriver.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.install
  stanford_profile_helper.module
  stanford_profile_helper.post_update.php
Labels: patch, size/s

#128 8.1.20
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xs

#129 D8CORE-4536: fixing the date alignment for an event list
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#130 "8.x-1.x 8.1.21
  CHANGELOG.md
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xs
