Repository SU-SWS/stanford_profile_helper, pull requests merged in 2021-03, with the labels that each got.

#77 D8CORE-3476 Create a new view display mode specific for viewfields
  stanford_profile_helper.module
Labels: size/xs

#74 D8CORE-3520 All Publications list page
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/lib/scss/_modular_spacing.scss
  src/EventSubscriber/EventSubscriber.php
  stanford_profile_helper.module
  stanford_profile_helper.post_update.php
  stanford_profile_helper.services.yml
  tests/src/Kernel/EventSubscriber/EventSubscriberTest.php
Labels: size/s

#79 update admin toolbar
  composer.json
Labels: size/xs

#80 D8CORE-3540: fixing the caption styling on the gallery.
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/gallery/index.scss
Labels: size/xs

#81 "8.x-1.x 8.1.9
  CHANGELOG.md
  composer.json
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/assets/svg/caret-right.svg
  modules/stanford_profile_styles/dist/assets/svg/lock-solid.svg
  modules/stanford_profile_styles/dist/assets/svg/lock.svg
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/assets/svg/arrow-right.svg
  modules/stanford_profile_styles/lib/assets/svg/arrow-up-right.svg
  modules/stanford_profile_styles/lib/assets/svg/caret-right.svg
  modules/stanford_profile_styles/lib/assets/svg/lock-solid.svg
  modules/stanford_profile_styles/lib/assets/svg/lock.svg
  modules/stanford_profile_styles/lib/scss/_modular_spacing.scss
  modules/stanford_profile_styles/lib/scss/base/views/search.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/gallery/index.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_profile_styles/webpack.config.js
  src/EventSubscriber/EventSubscriber.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.install
  stanford_profile_helper.module
  stanford_profile_helper.post_update.php
  stanford_profile_helper.services.yml
  templates/block--stanford-basic-search.html.twig
  tests/src/Kernel/EventSubscriber/EventSubscriberTest.php
Labels: patch, size/s

#82 D8CORE-3673: fixing the spacing after a title when it is in one column.
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#83 8.1.10
  CHANGELOG.md
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: patch, size/xs

#87 D8CORE-3957: Setting the event cards to only be one per row
  CHANGELOG.md
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/react_paragraphs/_multirow.scss
  stanford_profile_helper.info.yml
Labels: patch, size/xs

#86 D8CORE-3126 intranet functionality
  composer.json
  modules/stanford_intranet/.nvmrc
  modules/stanford_intranet/dist/css/base/intranet.css
  modules/stanford_intranet/lib/scss/base/intranet.scss
  modules/stanford_intranet/package-lock.json
  modules/stanford_intranet/package.json
  modules/stanford_intranet/src/Config/ConfigOverrider.php
  modules/stanford_intranet/src/Plugin/Field/FieldType/EntityAccessFieldType.php
  modules/stanford_intranet/src/Plugin/Field/FieldWidget/EntityAccessFieldWidget.php
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_intranet/stanford_intranet.install
  modules/stanford_intranet/stanford_intranet.module
  modules/stanford_intranet/stanford_intranet.services.yml
  modules/stanford_intranet/tests/src/Kernel/Config/ConfigOverriderTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_intranet/tests/src/Kernel/Plugin/Field/FieldWidget/EntityAccessFieldWidgetTest.php
  modules/stanford_intranet/webpack.config.js
  src/Plugin/Field/FieldWidget/SamlRoleMappingWidget.php
  stanford_profile_helper.module
  tests/src/Kernel/Plugin/Field/FieldWidget/SamlRoleMappingWidgetTest.php
Labels: patch, size/xl

#91 D8CORE-4021 Give site managers permission to assign custom roles
  src/Config/ConfigOverrides.php
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: size/s

#93 D8CORE-2853 Prevent unpublishing home, 403, or 404 pages
  stanford_profile_helper.module
Labels: size/xs
