Repository SU-SWS/stanford_profile_helper, pull requests merged in 2022-04, with the labels that each got.

#187 D8CORE-5615 Styles for shared tags view
  modules/stanford_profile_styles/dist/css/layout/layout.css
  modules/stanford_profile_styles/lib/scss/layout/layout.scss
  modules/stanford_profile_styles/stanford_profile_styles.module
  stanford_profile_helper.module
Labels: size/xs

#189 Drush command to easily set up intranets
  composer.json
  modules/stanford_intranet/drush.services.yml
  modules/stanford_intranet/src/Commands/IntranetCommands.php
  modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
Labels: size/s

#190 D8CORE-4128 Adjusted styles to change views to HTML lists
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#188 D8CORE-4842: removing the image when in 2-col
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#191 D8CORE-4728: updating decanter
  modules/stanford_basic_page_types/dist/css/component/basic-page-type-list.css
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/package-lock.json
  modules/stanford_basic_page_types/package.json
  modules/stanford_intranet/package-lock.json
  modules/stanford_intranet/package.json
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
Labels: size/xl

#193 D8CORE-5749: updating styles for shared tags
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#192 D8CORE-5567: utility classes for tables
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_table.scss
Labels: size/xs

#195 D8CORE-5771: limited stripes to tbody only
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_table.scss
Labels: size/xs

#194 D8CORE-5729: moving to the profile helper
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/lib/scss/base/stanford_profile_styles.scss
  modules/stanford_profile_styles/stanford_profile_styles.module
Labels: size/xs

#196 D8CORE-5748: adding unstyle list to the term list
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#197 D8CORE-5686 Adjusted scheduler help text
  stanford_profile_helper.module
Labels: size/xs

#198 D8CORE-5750 Modify field render arrays to better suite the DS module limits
  stanford_profile_helper.module
  stanford_profile_helper.services.yml
Labels: size/xs
