Repository SU-SWS/stanford_profile_helper, pull requests merged in 2022-05, with the labels that each got.

#199 Updated dev dependencies
  composer.json
Labels: size/xs

#200 8.1.35
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/dist/css/component/basic-page-type-list.css
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
  modules/stanford_basic_page_types/package-lock.json
  modules/stanford_basic_page_types/package.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/drush.services.yml
  modules/stanford_intranet/package-lock.json
  modules/stanford_intranet/package.json
  modules/stanford_intranet/src/Commands/IntranetCommands.php
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/dist/css/layout/layout.css
  modules/stanford_profile_styles/lib/scss/base/stanford_profile_styles.scss
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_table.scss
  modules/stanford_profile_styles/lib/scss/layout/layout.scss
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
  stanford_profile_helper.services.yml
Labels: size/xl, minor

#201 D8CORE-5829: set up the footer text to inherit the smaller size
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
Labels: size/xs

#202 Update hook and drush command to move all public files into private file system.
  modules/stanford_intranet/drush.services.yml
  modules/stanford_intranet/src/Commands/IntranetCommands.php
  modules/stanford_intranet/src/StanfordIntranetManager.php
  modules/stanford_intranet/src/StanfordIntranetManagerInterface.php
  modules/stanford_intranet/stanford_intranet.install
  modules/stanford_intranet/stanford_intranet.services.yml
  modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_intranet/tests/src/Kernel/StanfordIntranetManagerTest.php
Labels: size/s

#203 8.2.1
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/drush.services.yml
  modules/stanford_intranet/src/Commands/IntranetCommands.php
  modules/stanford_intranet/src/StanfordIntranetManager.php
  modules/stanford_intranet/src/StanfordIntranetManagerInterface.php
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_intranet/stanford_intranet.install
  modules/stanford_intranet/stanford_intranet.services.yml
  modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_intranet/tests/src/Kernel/StanfordIntranetManagerTest.php
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
Labels: patch

#204 8.2.1
  composer.json
Labels: patch

#205 Added conditional to fix null fatal error on 8102 update.
  stanford_profile_helper.post_update.php
Labels: size/xs

#206 8.2.2
  CHANGELOG.md
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.post_update.php
Labels: size/xs, patch

#207 D8CORE-5837: fixup for the transparent hover
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_headings.scss
Labels: size/xs, patch

#208 8.2.3
  CHANGELOG.md
  composer.json
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_headings.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: size/xs, patch
