Repository SU-SWS/stanford_profile_helper, pull requests merged in 2022-11, with the labels that each got.

#218 D8CORE-5865: Prevented spaces from being stripped from course code
  modules/stanford_courses/templates/components/course-list/course-item-list.twig
  modules/stanford_courses/templates/components/course-vertical-teaser/course-vertical-teaser.twig
Labels: size/xs

#217 D8CORE-2932: removing extra spacing on people unstyled lists
  modules/stanford_person/dist/css/stanford_person.views.css
  modules/stanford_person/lib/scss/stanford_person.views.scss
Labels: size/xs

#219 Override page_cache_query_ignore settings with view queries
  src/Config/ConfigOverrides.php
  stanford_profile_helper.post_update.php
Labels: size/xs

#220 9.0.3
  .github/workflows/release.yml
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_courses/templates/components/course-list/course-item-list.twig
  modules/stanford_courses/templates/components/course-vertical-teaser/course-vertical-teaser.twig
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/dist/css/stanford_person.views.css
  modules/stanford_person/lib/scss/stanford_person.views.scss
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/Config/ConfigOverrides.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.post_update.php
Labels: size/s, patch

#221 9.0.4
  .gitignore
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/dist/js/news-list.behaviors.js
  modules/stanford_news/dist/js/news-list.behaviors.js.map
  modules/stanford_news/dist/js/news-node.behaviors.js
  modules/stanford_news/dist/js/news-node.behaviors.js.map
  modules/stanford_news/lib/js/stanford_news.behavior.js
  modules/stanford_news/package-lock.json
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_news/stanford_news.module
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: patch, size/xl

#223 release 9.0.5
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#224 9.0.6
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/Config/ConfigOverrides.php
  stanford_profile_helper.info.yml
Labels: size/xs, patch
