Repository SU-SWS/stanford_profile_helper, pull requests merged in 2023-09, with the labels that each got.

#266 Add response_code_condition replacing the contrib module
  composer.json
  modules/jumpstart_ui/jumpstart_ui.module
  modules/response_code_condition/response_code_condition.info.yml
  modules/response_code_condition/src/Plugin/Condition/ResponseCodeCondition.php
  modules/response_code_condition/tests/src/Unit/Plugin/Condition/ResponseCodeConditionTest.php
Labels: size/s, patch

#267 9.3.0
  .github/workflows/release.yml
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, minor

#265 D8CORE-6824: Spacer paragraph - changed label of default value
  src/EventSubscriber/FormEventSubscriber.php
  stanford_profile_helper.info.yml
  tests/src/Kernel/EventSubscriber/FormEventSubscriberTest.php
  tests/src/Kernel/SuProfileHelperKernelTestBase.php
Labels: size/s, patch

#268 Update unit tests for d10
  .github/workflows/tests.yml
  composer.json
  modules/jumpstart_ui/tests/src/Kernel/Pattern/PatternMediaTest.php
  modules/jumpstart_ui/tests/src/Unit/Layouts/JumpstartUiLayoutsTest.php
  modules/jumpstart_ui/tests/src/Unit/Layouts/JumpstartUiThreeColumnLayoutTest.php
  modules/jumpstart_ui/tests/src/Unit/Layouts/JumpstartUiTwoColumnLayoutTest.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/Block/PageHeadingBlockTest.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/Block/SkipNavAnchorBlockTest.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/TwigPlugin/JumpstartUITwigTest.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/paragraphs/Behavior/HeroPatternBehaviorTest.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/paragraphs/Behavior/ListParagraphBehaviorTest.php
  modules/response_code_condition/tests/src/Unit/Plugin/Condition/ResponseCodeConditionTest.php
  modules/stanford_courses/modules/stanford_courses_importer/tests/Kernel/Plugin/migrate/process/ExploreCoursesMigrationPluginsTest.php
  modules/stanford_courses/tests/src/Kernel/Plugin/Field/FieldWidget/ExploreCoursesUrlWidgetTest.php
  modules/stanford_events/modules/stanford_events_importer/tests/src/Kernel/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
  modules/stanford_events/modules/stanford_events_importer/tests/src/Unit/Config/ConfigOverridesTest.php
  modules/stanford_events/modules/stanford_events_importer/tests/src/Unit/StanfordEventsImporterTest.php
  modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_intranet/tests/src/Kernel/Plugin/Field/FieldWidget/EntityAccessFieldWidgetTest.php
  modules/stanford_intranet/tests/src/Kernel/StanfordIntranetManagerTest.php
  modules/stanford_news/tests/src/Unit/Plugin/Block/SignupBlockTest.php
  modules/stanford_notifications/src/Commands/StanfordNotificationsCommands.php
  modules/stanford_notifications/tests/src/Kernel/NotificationServiceTest.php
  modules/stanford_notifications/tests/src/Kernel/StanfordNotificationTestBase.php
  modules/stanford_paragraph_card/tests/src/Unit/Plugin/paragraphs/Behavior/CardBehaviorTest.php
  modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/CapTest.php
  modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
  modules/stanford_policy/tests/src/Kernel/EventSubscriber/StanfordPolicySubscriberTest.php
  modules/stanford_profile_drush/tests/src/Kernel/Commands/StanfordProfileCommandsTest.php
  modules/stanford_publication/tests/src/Kernel/PublicationTestBase.php
  tests/src/Kernel/EventSubscriber/FormEventSubscriberTest.php
  tests/src/Kernel/EventSubscriber/ViewsEventSubscriberTest.php
  tests/src/Kernel/Plugin/Field/FieldWidget/SamlRoleMappingWidgetTest.php
  tests/src/Kernel/SuProfileHelperKernelTestBase.php
Labels: size/s

#269 9.3.1
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#270 9.3.2
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#271 9.3.3
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#272 9.3.4
  CHANGELOG.md
  modules/jumpstart_ui/dist/templates/decanter/components/secondary-nav/secondary-nav.twig
  modules/jumpstart_ui/dist/templates/decanter/utilities/macros/link-list.twig
  modules/jumpstart_ui/dist/templates/decanter/utilities/macros/menu-loop.twig
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch
