Repository SU-SWS/stanford_profile_helper, pull requests merged in 2023-06, with the labels that each got.

#246 9.2.7
  .github/workflows/release.yml
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_layout_paragraphs/css/stanford_layout_paragraphs.node_form.css
  modules/stanford_layout_paragraphs/layouts/one_column/one-column.css
  modules/stanford_layout_paragraphs/layouts/two_column/two-column.css
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.module
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/Config/ConfigOverrides.php
  src/EventSubscriber/EntityEventSubscriber.php
  stanford_profile_helper.info.yml
Labels: patch

#245 D8CORE-4495: changing lineheight of past event note
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/dist/js/stanford_events.node.behaviors.js
  modules/stanford_events/lib/js/stanford_events.behavior.js
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs

#247 Revert "D8CORE-4495: changing lineheight of past event note"
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/dist/js/stanford_events.node.behaviors.js
  modules/stanford_events/lib/js/stanford_events.behavior.js
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs

#248 D8CORE-4495 | @jdwjdwjdw | Update past events list styles
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs

#249 D8CORE-6758 | @jdwjdwjdw | Fixup gallery h2 for layout paragraphs
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  stanford_profile_helper.info.yml
  tests/src/Kernel/EventSubscriber/FormEventSubscriberTest.php
  tests/src/Kernel/SuProfileHelperKernelTestBase.php
Labels: size/xs, patch

#250 9.2.8
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.module
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/s, patch

#252 Various tweaks to layout paragraphs form displays
  composer.json
  modules/stanford_layout_paragraphs/dist/css/node_form.css
  modules/stanford_layout_paragraphs/dist/webpack-assets.json
  modules/stanford_layout_paragraphs/scss/node_form.scss
  modules/stanford_layout_paragraphs/src/Controller/SuChooseComponentController.php
  modules/stanford_layout_paragraphs/src/EventSubscriber/StanfordLayoutParagraphsRouteSubscriber.php
  modules/stanford_layout_paragraphs/src/Layouts/TwoColumn.php
  modules/stanford_layout_paragraphs/src/Plugin/paragraphs/Behavior/LayoutParagraphs.php
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.module
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.services.yml
  modules/stanford_layout_paragraphs/tests/src/Kernel/EventSubscriber/StanfordLayoutParagraphsSubscriberTest.php
  modules/stanford_layout_paragraphs/tests/src/Kernel/Plugin/paragraphs/Behavior/LayoutParagraphsTest.php
Labels: size/s

#251 D8CORE-6761: added button and link styles to the layout paragraph preview
  modules/stanford_layout_paragraphs/dist/css/preview_paragraphs.css
  modules/stanford_layout_paragraphs/dist/css/preview_paragraphs.js
  modules/stanford_layout_paragraphs/scss/preview_paragraphs.scss
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.libraries.yml
  modules/stanford_layout_paragraphs/webpack.config.js
Labels: size/s

#253 D8CORE-4778: adding the underline to splash in theme
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
Labels: size/xs
