Repository SU-SWS/stanford_profile_helper, pull requests merged in 2023-05, with the labels that each got.

#232 Fixed the menu link content presave for the menu_link field module
  src/EventSubscriber/EntityEventSubscriber.php
Labels: size/xs

#233 9.2.1
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/EventSubscriber/EntityEventSubscriber.php
  src/EventSubscriber/FormEventSubscriber.php
  stanford_profile_helper.info.yml
Labels: size/s, patch

#234 Alter taxonomy form to provide a argument helper
  src/EventSubscriber/FormEventSubscriber.php
Labels: size/xs

#236 Fixup white bar above footer
  modules/stanford_intranet/lib/scss/base/intranet.scss
Labels: size/xs

#237 9.2.2
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/lib/scss/base/intranet.scss
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/EventSubscriber/FormEventSubscriber.php
  stanford_profile_helper.info.yml
Labels: size/s, patch

#238 9.2.3
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/EventSubscriber/FormEventSubscriber.php
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#239 Copy work from SUL over for decoupled tools
  composer.json
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.module
  modules/stanford_profile_styles/stanford_profile_styles.module
  src/Plugin/Filter/SuCleanHtml.php
  stanford_profile_helper.libraries.yml
  stanford_profile_helper.module
  tests/src/Unit/Plugin/Filter/SuCleanHtmlTest.php
Labels: size/s

#240 9.2.4
  CHANGELOG.md
  composer.json
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.module
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/Plugin/Filter/SuCleanHtml.php
  stanford_profile_helper.info.yml
  stanford_profile_helper.libraries.yml
  stanford_profile_helper.module
  tests/src/Unit/Plugin/Filter/SuCleanHtmlTest.php
Labels: size/s, patch

#241 9.2.5
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/Plugin/jsonapi/FieldEnhancer/Base64Image.php
  stanford_profile_helper.info.yml
Labels: size/s, patch

#242 9.2.6
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  src/EventSubscriber/FormEventSubscriber.php
  src/Plugin/jsonapi/FieldEnhancer/Base64Image.php
  stanford_profile_helper.info.yml
Labels: size/xs, patch
