Repository SU-SWS/stanford_profile_helper, pull requests merged in 2023-08, with the labels that each got.

#261 SDSS-763: Check for number of regions on banner restriction.
  modules/stanford_layout_paragraphs/src/EventSubscriber/StanfordLayoutParagraphsSubscriber.php
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.services.yml
Labels: size/xs

#263 Release 9.2.15
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_layout_paragraphs/src/EventSubscriber/StanfordLayoutParagraphsSubscriber.php
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.services.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#264 D8CORE-4495 | @jdwjdwjdw | Update past events text on node page
  modules/stanford_events/dist/js/stanford_events.node.behaviors.js
  modules/stanford_events/dist/js/stanford_events.node.behaviors.js.map
  modules/stanford_events/lib/js/stanford_events.behavior.js
Labels: size/xs

#262 D8CORE-6802 Update preview styles with most of the front end styles
  modules/jumpstart_ui/jumpstart_ui.libraries.yml
  modules/jumpstart_ui/templates/components/card/card.ui_patterns.yml
  modules/jumpstart_ui/templates/components/date-stacked/date-stacked.ui_patterns.yml
  modules/jumpstart_ui/templates/components/hero/hero.ui_patterns.yml
  modules/jumpstart_ui/templates/components/media/media.ui_patterns.yml
  modules/stanford_events/stanford_events.libraries.yml
  modules/stanford_events/templates/components/card/card.html.twig
  modules/stanford_events/templates/components/card/card.ui_patterns.yml
  modules/stanford_events/templates/components/list/list.ui_patterns.yml
  modules/stanford_layout_paragraphs/.nvmrc
  modules/stanford_layout_paragraphs/dist/css/node_form.css
  modules/stanford_layout_paragraphs/dist/css/preview_paragraphs.css
  modules/stanford_layout_paragraphs/dist/webpack-assets.json
  modules/stanford_layout_paragraphs/js/stanford_layout_paragraphs.layout_paragraphs.js
  modules/stanford_layout_paragraphs/scss/node_form.scss
  modules/stanford_layout_paragraphs/scss/preview_paragraphs.scss
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.module
  modules/stanford_layout_paragraphs/yarn.lock
  modules/stanford_news/stanford_news.libraries.yml
  modules/stanford_news/templates/components/news-vertical-teaser/news-vertical-teaser.ui_patterns.yml
Labels: patch, size/l
