Repository SU-SWS/stanford_profile_helper, pull requests merged in 2024-02, with the labels that each got.

#293 9.5.0
  CHANGELOG.md
  modules/stanford_publication/tests/src/Kernel/Entity/CitationTest.php
  stanford_profile_helper.info.yml
Labels: size/xs, minor

#295 9.5.1
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_decoupled/stanford_decoupled.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#289 Updated help text for publishing scheduler
  stanford_profile_helper.module
Labels: size/xs

#297 Add graphql_composer dependency
  composer.json
Labels: size/xs

#298 D8CORE-7212 | @jdwjdwjdw | Update "Teaser" paragraph type styles
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
  modules/stanford_courses/dist/css/course-vertical-teaser.css
  modules/stanford_courses/lib/scss/course-vertical-teaser.scss
  modules/stanford_events/dist/css/stanford_events.event-card.css
  modules/stanford_events/lib/scss/components/event-card/stanford_events.event-card.scss
  modules/stanford_news/dist/css/news-vertical-teaser.css
  modules/stanford_news/lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xs

#294 D8CORE-7212 Add behavior to teaser paragraph to change headers to h3
  modules/jumpstart_ui/dist/templates/decanter/components/card/card.twig
  modules/jumpstart_ui/jumpstart_ui.install
  modules/jumpstart_ui/src/Plugin/paragraphs/Behavior/ListParagraphBehavior.php
  modules/jumpstart_ui/src/Plugin/paragraphs/Behavior/TeaserParagraphBehavior.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/paragraphs/Behavior/TeaserParagraphBehaviorTest.php
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/_basic-page-types.scss
  modules/stanford_courses/dist/css/course-list-item.css
  modules/stanford_courses/dist/css/course-vertical-teaser.css
  modules/stanford_courses/lib/scss/course-list-item.scss
  modules/stanford_courses/lib/scss/course-vertical-teaser.scss
  modules/stanford_courses/templates/components/course-list/course-item-list.twig
  modules/stanford_courses/templates/components/course-list/course-list.ui_patterns.yml
  modules/stanford_courses/templates/components/course-vertical-teaser/course-vertical-teaser.twig
  modules/stanford_courses/templates/components/course-vertical-teaser/course-vertical-teaser.ui_patterns.yml
  modules/stanford_courses/yarn.lock
  modules/stanford_events/dist/css/stanford_events.event-card.css
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/lib/scss/components/event-card/stanford_events.event-card.scss
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
  modules/stanford_events/templates/components/card/card.html.twig
  modules/stanford_events/templates/components/card/card.ui_patterns.yml
  modules/stanford_events/templates/components/list/list.html.twig
  modules/stanford_events/templates/components/list/list.ui_patterns.yml
  modules/stanford_events/yarn.lock
  modules/stanford_news/dist/css/news-list-item.css
  modules/stanford_news/dist/css/news-vertical-teaser.css
  modules/stanford_news/lib/scss/components/news-list-item/_list-item.scss
  modules/stanford_news/lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
  modules/stanford_news/templates/components/news-list/news-item-list.twig
  modules/stanford_news/templates/components/news-list/news-list.ui_patterns.yml
  modules/stanford_news/templates/components/news-vertical-teaser/news-vertical-teaser.twig
  modules/stanford_news/templates/components/news-vertical-teaser/news-vertical-teaser.ui_patterns.yml
  modules/stanford_news/yarn.lock
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xl
