Repository SU-SWS/stanford_profile_helper, pull requests merged in 2025-02, with the labels that each got.

#366 Modify space in two and three column layouts between components
  CHANGELOG.md
  composer.json
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#367 Add hook to support extlink module 2.0+
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_layout_paragraphs/layouts/three_column/three-column.css
  modules/stanford_layout_paragraphs/layouts/two_column/two-column.css
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/lib/scss/base/stanford_profile_styles.scss
  modules/stanford_profile_styles/package.json
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_profile_styles/yarn.lock
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
  stanford_profile_helper.module
Labels: size/m, patch

#369 D8CORE-7785: spacing on basic page list
  modules/stanford_profile_styles/dist/css/component/paragraph/lists.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/lists/index.scss
Labels: size/xs

#368 D8CORE-7726: adding space for touch targets on Events node taxonomy terms.
  modules/stanford_events/dist/css/stanford_events.node.css
  modules/stanford_events/lib/scss/stanford_events.node.scss
Labels: size/xs

#374 D8CORE-7641: formatted the spacing on search page
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/lib/scss/base/views/search.scss
Labels: size/xs

#378 D8CORE-7662: Created a single column layout to added the filtered paragraph
  modules/stanford_layout_paragraphs/layouts/one_column_filters/layout-paragraphs-one-column-filters.html.twig
  modules/stanford_layout_paragraphs/layouts/one_column_filters/one-column-filters.css
  modules/stanford_layout_paragraphs/src/Layouts/OneColumnFilters.php
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.layouts.yml
  modules/stanford_layout_paragraphs/stanford_layout_paragraphs.libraries.yml
Labels: size/xs

#353 D8CORE-7660: Styling for opportunities content type.
  modules/stanford_profile_styles/dist/css/component/node/stanford_opportunity.css
  modules/stanford_profile_styles/dist/css/component/paragraph/entity.css
  modules/stanford_profile_styles/dist/css/component/paragraph/lists.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_opportunity.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/entity/index.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/lists/index.scss
Labels: size/s
