Repository SU-SWS/stanford_profile_helper, pull requests merged in 2025-07, with the labels that each got.

#412 Alter basic auth provider to be global for all routes
  modules/stanford_decoupled/src/StanfordDecoupledServiceProvider.php
  modules/stanford_decoupled/tests/src/Kernel/StanfordDecoupledServiceProviderTest.php
Labels: size/xs

#413 9.10.2
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch

#414 Use route alter instead of service provider for private file basic auth access
  modules/stanford_decoupled/src/EventSubscriber/StanfordDecoupledRouteSubscriber.php
  modules/stanford_decoupled/src/StanfordDecoupledServiceProvider.php
  modules/stanford_decoupled/stanford_decoupled.services.yml
  modules/stanford_decoupled/tests/src/Kernel/EventSubscriber/StanfordDecoupledRouteSubscriberTest.php
  modules/stanford_decoupled/tests/src/Kernel/StanfordDecoupledServiceProviderTest.php
Labels: size/xs, size/s

#417 D8CORE-7666: A11y: Updated line-height on a person node.
  modules/stanford_person/dist/css/stanford_person.node.css
  modules/stanford_person/lib/scss/stanford_person.node.scss
Labels: size/xs
