Repository SU-SWS/stanford_profile_helper, pull requests merged in 2025-06, with the labels that each got.

#407 D8CORE-7574: Updated spacing on Events' contact to be a11y compliant
  modules/stanford_events/dist/css/stanford_events.node.css
  modules/stanford_events/lib/scss/stanford_events.node.scss
Labels: size/xs

#404 D8CORE-8019: Updating spacing on Opportunity node right column.
  modules/stanford_profile_styles/dist/css/component/node/stanford_opportunity.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_opportunity.scss
Labels: size/xs

#409 UE-536: Corrected mobile layout and some spacing issues
  modules/stanford_profile_styles/dist/css/component/node/stanford_opportunity.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_opportunity.scss
Labels: size/xs, size/s

#411 9.10.1
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
  yarn.lock
Labels: size/xs, patch
