Repository SU-SWS/stanford_profile_helper, pull requests merged in 2025-08, with the labels that each got.

#421 D8CORE-8075: Add option for veritical dividers on 2 and 3 column layouts
  modules/stanford_layout_paragraphs/dist/css/layouts/three-column.css
  modules/stanford_layout_paragraphs/dist/css/layouts/two-column.css
  modules/stanford_layout_paragraphs/layouts/three_column/layout-paragraphs-three-column.html.twig
  modules/stanford_layout_paragraphs/layouts/three_column/three-column.scss
  modules/stanford_layout_paragraphs/layouts/two_column/layout-paragraphs-two-column.html.twig
  modules/stanford_layout_paragraphs/layouts/two_column/two-column.scss
  modules/stanford_layout_paragraphs/package.json
  modules/stanford_layout_paragraphs/src/Layouts/LayoutWithBgColorTrait.php
  modules/stanford_layout_paragraphs/src/Layouts/OneColumn.php
  modules/stanford_layout_paragraphs/src/Layouts/ThreeColumn.php
  modules/stanford_layout_paragraphs/src/Layouts/TwoColumn.php
Labels: size/s

#423 D8CORE-7585: Changed search page background color
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/lib/scss/base/views/search.scss
Labels: size/xs

#426 D8CORE-8276: Updated the search background color
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/lib/scss/base/views/search.scss
Labels: size/xs

#428 10.0.0
  .github/workflows/release.yml
  CHANGELOG.md
  composer.json
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, major
