Repository SU-SWS/stanford_profile_helper, pull requests merged in 2025-01, with the labels that each got.

#356 D8CORE-7678: removed medium and small quotes
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
Labels: size/xs

#357 D8CORE-7531: removed max-width
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
Labels: size/xs

#361 D8CORE-7633: added aria-live: polite to the modal
  modules/stanford_profile_styles/js/colorbox.js
Labels: size/xs

#360 D8CORE-7751: tighten up event list spacing
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs

#358 D8CORE-7722: margin bottom zero on last item
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs

#359 D8CORE-7749: tighten spacing on news list
  modules/stanford_news/dist/css/news-list-item.css
  modules/stanford_news/lib/scss/components/news-list-item/_list-item.scss
Labels: size/xs

#362 D8CORE-7781: working on layouts. Stashing.
  modules/stanford_layout_paragraphs/layouts/one_column/one-column.css
  modules/stanford_layout_paragraphs/layouts/three_column/three-column.css
  modules/stanford_layout_paragraphs/layouts/two_column/two-column.css
Labels: size/xs

#363 D8CORE-7722 D8CORE-7751: design tweaks
  modules/stanford_events/dist/css/stanford_events.event-list.css
  modules/stanford_events/lib/scss/components/event-list/stanford_events.event-list.scss
  modules/stanford_news/dist/css/news-list-item.css
  modules/stanford_news/lib/scss/components/news-list-item/_list-item.scss
Labels: size/xs

#364 D8CORE-7753: Refactor accordion to use button and aria attributes
  modules/jumpstart_ui/dist/css/accordion.css
  modules/jumpstart_ui/dist/css/jumpstart_ui.base.css
  modules/jumpstart_ui/lib/scss/components/accordion.component.scss
  modules/jumpstart_ui/package.json
  modules/jumpstart_ui/templates/components/accordion/accordion.html.twig
  modules/jumpstart_ui/templates/components/accordion/accordion.js
  modules/jumpstart_ui/templates/components/accordion/accordion.ui_patterns.yml
  modules/jumpstart_ui/yarn.lock
Labels: size/m

#365 9.8.10
  CHANGELOG.md
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  stanford_profile_helper.info.yml
Labels: size/xs, patch
